-- EE476 Lab 1 progress portal — Supabase database setup
--
-- Before running this file, replace REPLACE_WITH_INSTRUCTOR_EMAIL near the
-- bottom with the instructor's real email address. Run the complete script in
-- the Supabase SQL Editor. It is safe to rerun after a successful setup.

begin;

-- ---------------------------------------------------------------------------
-- 1. Course roster and activated user profiles
-- ---------------------------------------------------------------------------
create table if not exists public.course_roster (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  roll_number text unique,
  full_name text not null,
  role text not null default 'student' check (role in ('student', 'instructor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (role = 'instructor' or roll_number is not null)
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  roster_id bigint not null unique references public.course_roster(id) on delete cascade,
  email text not null unique,
  roll_number text,
  full_name text not null,
  role text not null check (role in ('student', 'instructor')),
  activated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. Lab tasks, student completion state, and audit history
-- ---------------------------------------------------------------------------
create table if not exists public.lab_tasks (
  task_id text primary key,
  lab_id text not null,
  task_order integer not null check (task_order > 0),
  title text not null,
  unique (lab_id, task_order)
);

insert into public.lab_tasks (task_id, lab_id, task_order, title) values
  ('lab1-task-1', 'lab-1', 1, 'Environment setup'),
  ('lab1-task-2', 'lab-1', 2, 'RTL simulation'),
  ('lab1-task-3', 'lab-1', 3, 'Synthesis without DFT'),
  ('lab1-task-4', 'lab-1', 4, 'Equivalence and cell model'),
  ('lab1-task-5', 'lab-1', 5, 'Physical implementation'),
  ('lab1-task-6', 'lab-1', 6, 'Timing analysis and closure'),
  ('lab1-task-7', 'lab-1', 7, 'Gate-level simulation')
on conflict (task_id) do update set
  lab_id = excluded.lab_id,
  task_order = excluded.task_order,
  title = excluded.title;

create table if not exists public.lab_progress (
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  task_id text not null references public.lab_tasks(task_id) on delete cascade,
  completed boolean not null default true,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, task_id)
);

create table if not exists public.lab_progress_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  task_id text not null references public.lab_tasks(task_id) on delete cascade,
  completed boolean not null,
  changed_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. Timestamp and audit triggers
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists course_roster_touch_updated_at on public.course_roster;
create trigger course_roster_touch_updated_at
before update on public.course_roster
for each row execute function public.touch_updated_at();

create or replace function public.set_lab_progress_timestamps()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  if not new.completed then
    new.completed_at := null;
  elsif tg_op = 'INSERT' then
    new.completed_at := now();
  elsif old.completed is distinct from true then
    new.completed_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists lab_progress_set_timestamps on public.lab_progress;
create trigger lab_progress_set_timestamps
before insert or update on public.lab_progress
for each row execute function public.set_lab_progress_timestamps();

create or replace function public.audit_lab_progress_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.lab_progress_history (user_id, task_id, completed, changed_at)
  values (new.user_id, new.task_id, new.completed, now());
  return new;
end;
$$;

drop trigger if exists lab_progress_audit on public.lab_progress;
create trigger lab_progress_audit
after insert or update of completed on public.lab_progress
for each row execute function public.audit_lab_progress_change();

-- ---------------------------------------------------------------------------
-- 4. Roster activation and role checks
-- ---------------------------------------------------------------------------
create or replace function public.activate_roster_profile()
returns table (
  user_id uuid,
  email text,
  roll_number text,
  full_name text,
  role text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  login_email text;
  roster_record public.course_roster%rowtype;
  profile_record public.profiles%rowtype;
begin
  login_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  if auth.uid() is null or login_email = '' then
    raise exception 'Authentication is required.';
  end if;

  select roster.* into roster_record
  from public.course_roster as roster
  where roster.email = login_email;

  if not found then
    raise exception 'This email address is not in the course roster.';
  end if;

  insert into public.profiles (
    user_id,
    roster_id,
    email,
    roll_number,
    full_name,
    role
  ) values (
    auth.uid(),
    roster_record.id,
    roster_record.email,
    roster_record.roll_number,
    roster_record.full_name,
    roster_record.role
  )
  on conflict (user_id) do update set
    roster_id = excluded.roster_id,
    email = excluded.email,
    roll_number = excluded.roll_number,
    full_name = excluded.full_name,
    role = excluded.role
  returning * into profile_record;

  return query select
    profile_record.user_id,
    profile_record.email,
    profile_record.roll_number,
    profile_record.full_name,
    profile_record.role;
end;
$$;

create or replace function public.current_user_is_instructor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'instructor'
  );
$$;

-- ---------------------------------------------------------------------------
-- 5. Instructor-only class dashboard function
-- ---------------------------------------------------------------------------
create or replace function public.instructor_lab_progress(requested_lab_id text)
returns table (
  roster_id bigint,
  roll_number text,
  full_name text,
  email text,
  activated boolean,
  completed_count bigint,
  completed_task_ids jsonb,
  last_update timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_instructor() then
    raise exception 'Instructor access is required.';
  end if;

  return query
  select
    roster.id as roster_id,
    roster.roll_number,
    roster.full_name,
    roster.email,
    profile.user_id is not null as activated,
    count(task.task_id) filter (where progress.completed is true) as completed_count,
    coalesce(
      jsonb_agg(task.task_id order by task.task_order)
        filter (where progress.completed is true),
      '[]'::jsonb
    ) as completed_task_ids,
    max(progress.updated_at) filter (where task.lab_id = requested_lab_id) as last_update
  from public.course_roster as roster
  left join public.profiles as profile
    on profile.roster_id = roster.id
  left join public.lab_progress as progress
    on progress.user_id = profile.user_id
  left join public.lab_tasks as task
    on task.task_id = progress.task_id
   and task.lab_id = requested_lab_id
  where roster.role = 'student'
  group by
    roster.id,
    roster.roll_number,
    roster.full_name,
    roster.email,
    profile.user_id
  order by roster.roll_number, roster.full_name;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. Row-level security
-- ---------------------------------------------------------------------------
alter table public.course_roster enable row level security;
alter table public.profiles enable row level security;
alter table public.lab_tasks enable row level security;
alter table public.lab_progress enable row level security;
alter table public.lab_progress_history enable row level security;

drop policy if exists "Instructor manages roster" on public.course_roster;
create policy "Instructor manages roster"
on public.course_roster
for all
to authenticated
using (public.current_user_is_instructor())
with check (public.current_user_is_instructor());

drop policy if exists "Users read own profile; instructor reads all" on public.profiles;
create policy "Users read own profile; instructor reads all"
on public.profiles
for select
to authenticated
using (user_id = auth.uid() or public.current_user_is_instructor());

drop policy if exists "Authenticated users read lab tasks" on public.lab_tasks;
create policy "Authenticated users read lab tasks"
on public.lab_tasks
for select
to authenticated
using (auth.uid() is not null);

drop policy if exists "Users and instructor read progress" on public.lab_progress;
create policy "Users and instructor read progress"
on public.lab_progress
for select
to authenticated
using (user_id = auth.uid() or public.current_user_is_instructor());

drop policy if exists "Students create own progress" on public.lab_progress;
create policy "Students create own progress"
on public.lab_progress
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'student'
  )
);

drop policy if exists "Students update own progress" on public.lab_progress;
create policy "Students update own progress"
on public.lab_progress
for update
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'student'
  )
);

drop policy if exists "Instructor reads progress history" on public.lab_progress_history;
create policy "Instructor reads progress history"
on public.lab_progress_history
for select
to authenticated
using (public.current_user_is_instructor());

-- Explicit API permissions; row-level security still controls every row.
grant select, insert, update on public.course_roster to authenticated;
grant select on public.profiles to authenticated;
grant select on public.lab_tasks to authenticated;
grant select, insert, update on public.lab_progress to authenticated;
grant select on public.lab_progress_history to authenticated;
grant usage, select on sequence public.course_roster_id_seq to authenticated;

revoke all on function public.activate_roster_profile() from public;
grant execute on function public.activate_roster_profile() to authenticated;
revoke all on function public.current_user_is_instructor() from public;
grant execute on function public.current_user_is_instructor() to authenticated;
revoke all on function public.instructor_lab_progress(text) from public;
grant execute on function public.instructor_lab_progress(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 7. Bootstrap the first instructor
-- Replace the placeholder before running this script.
-- ---------------------------------------------------------------------------
do $$
declare
  instructor_email text := lower('rehan.naeem@uet.edu.pk');
begin
  insert into public.course_roster (
    email,
    roll_number,
    full_name,
    role
  )
  values (
    instructor_email,
    null,
    'Rehan Naeem',
    'instructor'
  )
  on conflict (email) do update set
    role = 'instructor',
    full_name = excluded.full_name,
    roll_number = null;
end;
$$;

commit;
