-- Lab 04 progress registration
-- Run this once in Supabase SQL Editor after the original lab progress setup.
-- These IDs must match the Lab 04 objective order in lab-manual(9).html.

begin;

insert into public.lab_tasks (task_id, lab_id, task_order, title) values
  ('lab4-objective-1',  'lab-4',  1, 'Apply a complete RTL-to-GDSII flow'),
  ('lab4-objective-2',  'lab-4',  2, 'Verify RTL functional correctness'),
  ('lab4-objective-3',  'lab-4',  3, 'Develop and apply design constraints'),
  ('lab4-objective-4',  'lab-4',  4, 'Perform logic synthesis and analyze the netlist'),
  ('lab4-objective-5',  'lab-4',  5, 'Analyze synthesis timing, power, area, and design checks'),
  ('lab4-objective-6',  'lab-4',  6, 'Perform the physical implementation flow'),
  ('lab4-objective-7',  'lab-4',  7, 'Identify timing and physical-design problems'),
  ('lab4-objective-8',  'lab-4',  8, 'Optimize selected performance, power, or area metrics'),
  ('lab4-objective-9',  'lab-4',  9, 'Compare baseline and optimized implementations'),
  ('lab4-objective-10', 'lab-4', 10, 'Evaluate performance, power, and area trade-offs'),
  ('lab4-objective-11', 'lab-4', 11, 'Generate and verify the final layout')
on conflict (task_id) do update set
  lab_id = excluded.lab_id,
  task_order = excluded.task_order,
  title = excluded.title;

commit;

-- When Lab 02 or Lab 03 is finalized:
-- 1. Replace its placeholder <li> elements with real objectives and remove
--    class="placeholder-copy".
-- 2. Register matching IDs here or in a new incremental SQL file. The IDs
--    generated by the page will be lab2-objective-1, lab2-objective-2, ...
--    and lab3-objective-1, lab3-objective-2, ... in displayed order.
